hydra:
  run:
    dir: ckpts/${model.name}_${model.mel_spec.mel_spec_type}_${model.tokenizer}_${datasets.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

datasets:
  name: KCVTTS
  batch_size_per_gpu: 3200
  batch_size_type: frame
  max_samples: 64
  num_workers: 0

optim:
  epochs: 50
  learning_rate: 2e-4
  num_warmup_updates: 4000
  grad_accumulation_steps: 2
  max_grad_norm: 1.0
  bnb_optimizer: False

model:
  name: Mamba3TTS_Base
  tokenizer: pinyin
  tokenizer_path: null
  backbone: Mamba3Backbone
  arch:
    dim: 1024
    depth: 22
    ff_mult: 2
    text_dim: 512
    text_mask_padding: True
    conv_layers: 4
    checkpoint_activations: False
    dropout: 0.0
    d_state: 128
    headdim: 64
    ngroups: 1
    rope_fraction: 0.5
    is_mimo: False
    mimo_rank: 1
    chunk_size: 64
  mel_spec:
    target_sample_rate: 24000
    n_mel_channels: 100
    hop_length: 256
    win_length: 1024
    n_fft: 1024
    mel_spec_type: vocos
  vocoder:
    is_local: False
    local_path: null

ckpts:
  logger: null
  wandb_project: Mamba3-TTS
  wandb_run_name: ${model.name}_${model.mel_spec.mel_spec_type}_${model.tokenizer}_${datasets.name}
  wandb_resume_id: null
  log_samples: false
  save_per_updates: 10000
  keep_last_n_checkpoints: 3
  last_per_updates: 2000
  save_dir: ckpts/${model.name}_${model.mel_spec.mel_spec_type}_${model.tokenizer}_${datasets.name}
